<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePropertiesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('properties', function (Blueprint $table) {
            // insert property columns
            $table->float('BathsTotal');
            $table->float('BedsTotal');
            $table->string('City');
            $table->decimal('ListPrice', 10, 2);
            $table->integer('MLSNumber')->primary();
            $table->string('Neighborhood');
            $table->string('PostalCode');
            $table->float('SqftTotal');
            $table->string('StateOrProvince');
            $table->string('StreetDirPrefix');
            $table->string('StreetName');
            $table->integer('StreetNumber');
            $table->string('StreetSuffix');
            $table->float('TaxAmount');
            $table->string('TransactionType');


            $table->text('AcceptingBackupOffersYN');
            $table->text('Access');
            $table->text('AcresCrop');
            $table->text('AcresCultivate');
            $table->text('AcresIrrigated');
            $table->text('AcresLeased');
            $table->text('AcresPasture');
            $table->text('ActiveOpenHouseCount');
            $table->text('AdditionalInformation');
            $table->text('ApplicationFee');
            $table->text('ArchitecturalStyle');
            $table->text('AssociationFeeFrequencyPrimary');
            $table->text('AssociationFeeFrequencySecondary');
            $table->text('AssociationFeeFrequencyTertiary');
            $table->text('AssociationFeeIncludes');
            $table->text('AssociationFeePrimary');
            $table->text('AssociationFeePrimaryAnnual');
            $table->text('AssociationFeeSecondary');
            $table->text('AssociationFeeSecondaryAnnual');
            $table->text('AssociationFeeTertiary');
            $table->text('AssociationFeeTertiaryAnnual');
            $table->text('AssociationFeeTotalAnnual');
            $table->text('AssociationNamePrimary');
            $table->text('AssociationNameSecondary');
            $table->text('AssociationNameTertiary');
            $table->text('AssociationPhonePrimary');
            $table->text('AssociationPhoneSecondary');
            $table->text('AssociationPhoneTertiary');
            $table->text('AuctionPrice');
            $table->text('AuctionPriceType');
            $table->text('AvailableAmps');
            $table->text('BasementCeilingHeight');
            $table->text('BasementFinishedYN');
            $table->text('BasementFloorType');
            $table->text('BasementPercentFinished');
            $table->text('BasementSize');
            $table->text('BasementType');
            $table->text('BathroomsTotalBasement');
            $table->text('BathroomsTotalLower');
            $table->text('BathroomsTotalMain');
            $table->text('BathroomsTotalUpper');
            $table->text('BathsFull');
            $table->text('BathsHalf');
            $table->text('BathsQuarter');
            $table->text('BathsThreeQuarter');
            $table->text('BedroomsTotalBasement');
            $table->text('BedroomsTotalLower');
            $table->text('BedroomsTotalMain');
            $table->text('BedroomsTotalUpper');
            $table->text('BuilderName1');
            $table->text('BuilderName2');
            $table->text('BuildingAreaSource');
            $table->text('BuildingName');
            $table->text('CloseDate');
            $table->text('ClosePrice');
            $table->text('CoListAgent_MUI');
            $table->text('CoListAgentDirectWorkPhone');
            $table->text('CoListAgentEmail');
            $table->text('CoListAgentFullName');
            $table->text('CoListAgentMLSID');
            $table->text('CoListOffice_MUI');
            $table->text('CoListOfficeMLSID');
            $table->text('CoListOfficeName');
            $table->text('CoListOfficePhone');
            $table->text('CommunityFeatures');
            $table->text('CondoFloorLocation');
            $table->text('CondoFloorLocationType');
            $table->text('CondoUnitOnEndYN');
            $table->text('ConstructionDetails');
            $table->text('ConstructionMaterials');
            $table->text('ConstructionMethods');
            $table->text('ContingentApprovalConditions');
            $table->text('ContractAddlTerms');
            $table->text('Cooling');
            $table->text('CoSellingAgent_MUI');
            $table->text('CoSellingAgentFullName');
            $table->text('CoSellingAgentMLSID');
            $table->text('CoSellingOffice_MUI');
            $table->text('CoSellingOfficeMLSID');
            $table->text('CoSellingOfficeName');
            $table->text('CountertopType');
            $table->text('Country');
            $table->text('CountyOrParish');
            $table->text('DepositsPotentiallyRefundable');
            $table->text('DevelopmentName');
            $table->text('Directions');
            $table->text('DistanceToBus');
            $table->text('DistanceToLightRail');
            $table->text('DistanceToOtherTransit');
            $table->text('DistanceType');
            $table->text('ElectricalService');
            $table->text('ElectricitySource');
            $table->text('ElementarySchool');
            $table->text('ExteriorFeatures');
            $table->text('FacesDirection');
            $table->text('Features');
            $table->text('Fencing');
            $table->text('FireplaceFeatures');
            $table->text('FireplaceLocations');
            $table->text('Flooring');
            $table->text('GasSource');
            $table->text('GasType');
            $table->text('GreenEnergyStarQualifiedYearCertified');
            $table->text('GreenHERSScore');
            $table->text('GreenHERSYearCertified');
            $table->text('GreenLEEDCertifiedLevel');
            $table->text('GreenLEEDYearCertified');
            $table->text('GreenNGBSICC700CertifiedLevel');
            $table->text('GreenNGBSICC700YearCertified');
            $table->text('GreenOtherCertifications');
            $table->text('GreenSolarKilowatts');
            $table->text('GreenSolarPVYearCertified');
            $table->text('GreenSolarThermalType');
            $table->text('GreenSolarThermalYearCertified');
            $table->text('HasHOAYN');
            $table->text('HasMultipleHOAsYN');
            $table->text('Heating');
            $table->text('HeatingFuel');
            $table->text('HighSchool');
            $table->text('HOAPrivateTransferFee');
            $table->text('HOAStatusLetterFee');
            $table->text('HOATransferAmount');
            $table->text('HomeEnergyScore');
            $table->text('HorseFacilityCount');
            $table->text('HorsePropertyFeatures');
            $table->text('HorsePropertyYN');
            $table->text('InteriorFeatures');
            $table->text('IrrigationType');
            $table->text('IsIncorporatedYN');
            $table->text('KitchenAppliances');
            $table->text('LandTopography');
            $table->text('Latitude');
            $table->text('LaundryAvailability');
            $table->text('LeaseDuration');
            $table->text('LeasingConditions');
            $table->text('ListAgent_MUI');
            $table->text('ListAgentDirectWorkPhone');
            $table->text('ListAgentEmail');
            $table->text('ListAgentFullName');
            $table->text('ListAgentMLSID');
            $table->text('ListingFinancing');
            $table->text('ListOffice_MUI');
            $table->text('ListOfficeMLSID');
            $table->text('ListOfficeName');
            $table->text('ListOfficePhone');
            $table->text('LivestockYN');
            $table->text('Longitude');
            $table->text('LotSizeAcres');
            $table->text('MaintainedBy');
            $table->text('Matrix_Unique_ID');
            $table->text('MatrixModifiedDT');
            $table->text('MiddleOrJuniorSchool');
            $table->text('Model');
            $table->text('NewHomeCommunityName');
            $table->text('NumberOfFireplaces');
            $table->text('OtherHVAC');
            $table->text('OutBuildingCount');
            $table->text('OutBuildingNumberOf');
            $table->text('OutBuildingsYN');
            $table->text('OwnerPaidUtilities');
            $table->text('ParcelNumber');
            $table->text('ParkingCount');
            $table->text('ParkingFeatures');
            $table->text('ParkingTotalSearchable');
            $table->text('PartialOwnershipAmount');
            $table->text('PartialOwnershipType');
            $table->text('PetDeposit');
            $table->text('PetRent');
            $table->text('PhotoCount');
            $table->text('PhotoModificationTimestamp');
            $table->text('PossibleUse');
            $table->text('PPA');
            $table->text('PropertySubType');
            $table->text('PropertyType');
            $table->text('PSFAboveGrade');
            $table->text('PSFFinished');
            $table->text('PSFTotal');
            $table->longText('PublicRemarks');
            $table->text('RentalApplication');
            $table->text('RentalsAllowed');
            $table->text('RentedDate');
            $table->text('RentedPrice');
            $table->text('RentQuotedPer');
            $table->text('ReportsAvailable');
            $table->text('Restrictions');
            $table->text('RestrictionsOther');
            $table->text('RoadSurface');
            $table->text('Roof');
            $table->text('RoughInYN');
            $table->text('SaleType');
            $table->text('SchoolDistrict');
            $table->text('SchoolOfChoiceYN');
            $table->text('SecurityDeposit');
            $table->text('SellerType');
            $table->text('SellingAgent_MUI');
            $table->text('SellingAgentFullName');
            $table->text('SellingAgentMLSID');
            $table->text('SellingOffice_MUI');
            $table->text('SellingOfficeMLSID');
            $table->text('SellingOfficeName');
            $table->text('Sewer');
            $table->longText('SiteFeatures');
            $table->text('SiteType');
            $table->text('SmartHomeFeatures');
            $table->text('SpecialAssessmentDescription');
            $table->float('SqFtFinished');
            $table->text('StateRegion', 15);
            $table->text('Status', 15);
            $table->timestamp('StatusChangeTimestamp');
            $table->text('StatusConditions');
            $table->text('StreetBuildingNumber');
            $table->text('StructuralStyle');
            $table->text('StyleCharacteristics');
            $table->text('Survey');
            $table->integer('TaxYear');
            $table->text('TenantPaidUtilities');
            $table->integer('TotalGarageSpaces');
            $table->text('UnderContractDate');
            $table->text('UnitAccess');
            $table->text('UnitNumber');
            $table->text('UnitNumberOfFloors');
            $table->text('Utilities');
            $table->text('Vegetation');
            $table->text('View');
            $table->text('VirtualTourURLUnbranded');
            $table->text('WaterMineralRights');
            $table->text('WaterSource');
            $table->text('WaterTapFee');
            $table->integer('YearBuilt');
            $table->text('Zoning');

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('properties');
    }
}
